//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by P2p.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_P2P_FORM                    101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_P2PTYPE                     129
#define IDR_MENU_TRAY                   130
#define IDI_ICON_TRAY_DISCONNECT        134
#define IDI_ICON_TRAY_CONNECT           135
#define IDB_TOOLBAR_1                   139
#define IDB_TOOLBAR_2                   140
#define IDD_DIALOG_CONNECT              150
#define IDB_BITMAP_CONNECT_TITLE        152
#define IDD_DIALOG_PREFERENCES          153
#define IDB_SKIN_MSN                    154
#define IDB_TOOLBAR_DIS                 155
#define IDB_TOOLBAR_DISABLE             155
#define IDD_SEARCH_VIEW                 156
#define IDD_DOWNLOADS_VIEW              157
#define IDD_UPLOADS_VIEW                158
#define IDD_SERVER_VIEW                 159
#define IDD_CHAT_VIEW                   160
#define IDI_ICON_STATUS_SERVERCOUNT     161
#define IDI_ICON_STATUS_DOWNLOADS       162
#define IDI_ICON_STATUS_UPLOADS         163
#define IDI_ICON_STATUS_HARD            164
#define IDI_ICON_VIEW_UPLOADS           172
#define IDI_ICON_VIEW_DOWNLOADS         173
#define IDD_DIALOG_MSN                  174
#define IDI_ICON_VIEW_SEARCH            176
#define IDD_TAB_SEARCH_VIEW_DETAIL      177
#define IDB_BITMAP_SEARCHTAB            178
#define IDI_ICON_VIEW_SERVER            179
#define IDI_ICON_VIEW_CHAT              180
#define IDI_ICON_LIST_LIBRARY_DISCONNECT 181
#define IDI_ICON_LIST_LIBRARY_CONNECT   182
#define IDR_MENU_SERVER_LIBRARY         183
#define IDD_TAB_PREFERENCE_CONNECT      185
#define IDD_TAB_PREFERENCE_DIRECTORY    186
#define IDD_TAB_PREFERENCE_DISPLAY      187
#define IDB_BITMAP_PREFERENCE_TAB       193
#define IDB_BITMAP_SEARCH_TAB           195
#define IDB_BITMAP_LIST_LIBRARY_CONNECT 198
#define IDR_MENU_TAB_SEARCH             199
#define IDB_BITMAP_MESSAGE_TITLE        200
#define IDR_MENU_TAB_UPDOWN             201
#define IDC_EDIT_SERVERNAME             1001
#define IDC_EDIT_USERID                 1003
#define IDC_RADIO_QUICKCONNECT          1005
#define IDC_RADIO_LIBRARY               1006
#define IDC_IPADDRESS_SERVERIP          1007
#define IDC_RADIO_CLIENT                1008
#define IDC_RADIO_SERVER                1009
#define IDC_BUTTON_NEW                  1011
#define IDC_BUTTON_CONNECT              1012
#define IDC_LIST_SERVER                 1014
#define IDC_BUTTON_TEST                 1015
#define IDC_BUTTON1                     1017
#define IDC_BUTTON_SEND                 1017
#define IDC_LIST_DOWNLOADS              1018
#define IDC_LIST_SELECT                 1019
#define IDC_STATIC_STATE                1020
#define IDC_CHECK_FOLDERSHARE           1021
#define IDC_CHECK_VIEWFOLDER            1021
#define IDC_LIST_UPLOADS                1022
#define IDC_COMBO_SERVERFILTER          1025
#define IDC_EDIT_SEARCHKEY              1026
#define IDC_BUTTON_SEARCH               1027
#define IDC_EDIT_SEARCHKEY2             1028
#define IDC_EDIT_POPUPTIME              1028
#define IDC_TAB_SEARCH                  1029
#define IDC_EDIT_SEARCHKEY3             1029
#define IDC_EDIT_TEMP                   1029
#define IDC_LIST_SEARCH                 1030
#define IDC_BUTTON_SEARCH2              1030
#define IDC_BUTTON_TEMP                 1030
#define IDC_TREE_EXPLORER               1031
#define IDC_EDIT_SEARCHKEY4             1031
#define IDC_EDIT_INCOMING               1031
#define IDC_EDIT_LOG                    1032
#define IDC_BUTTON_SEARCH3              1032
#define IDC_BUTTON_INCOMING             1032
#define IDC_EDIT_SHAREFOLDER            1033
#define IDC_BUTTON_SHAREFOLDER          1034
#define IDC_LIST3                       1036
#define IDC_CHECK1                      1037
#define IDC_CHECK_DELETE_COMPLETE       1037
#define IDC_CHECK2                      1038
#define IDC_CHECK_SHAREFOLDER           1038
#define IDC_SLIDER1                     1039
#define IDC_SLIDER_DOWNLOAD             1039
#define IDC_SLIDER2                     1040
#define IDC_SLIDER_UPLOAD               1040
#define IDC_TREE1                       1041
#define IDC_CHECK3                      1042
#define IDC_TAB_OPTION                  1042
#define IDC_CHECK_CONNECT               1042
#define IDC_CHECK4                      1043
#define IDC_STATIC_DOWNLOAD             1043
#define IDC_CHECK_DOWNLOAD              1043
#define IDC_CHECK5                      1044
#define IDC_STATIC_UPLOAD               1044
#define IDC_CHECK_DISCONNECT            1044
#define IDC_EDIT_CHAT                   1046
#define IDC_EDIT_SEND                   1047
#define IDC_STATIC_FREE                 1048
#define ID_FILE_SEARCH                  32771
#define ID_OPTION_MODIFY                32772
#define ID_BUTTON32779                  32773
#define ID_MENU_CHAT                    32774
#define ID_MENU_TEMP                    32775
#define ID_MENU_SEARCH                  32776
#define ID_MENU_DOWNLOADS               32777
#define ID_MENU_UPLOADS                 32778
#define ID_MENU_SERVER                  32779
#define ID_MENU_PREPERENCES             32780
#define ID_MENU_PREFERENCES             32781
#define ID_SERVER_CONNECT               32782
#define ID_SERVER_DISCONNECT            32783
#define ID_SERVER_LIBRARY_INSERT        32786
#define ID_SERVER_LIBRARY_DELETE        32787
#define ID_MENU_SERVER_CONNECT          32788
#define ID_MENU_SERVER_DISCONNECT       32789
#define ID_TAB_SEARCH_DELETE            32790
#define ID_TAB_UPDOWN_DELETE            32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
